# Generated by Django 4.0 on 2022-01-01 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_testorder_order_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='order_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.testordertype'),
        ),
    ]
