# Generated by Django 4.0 on 2022-01-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_testorder_completed_testorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Completed'), (0, 'Uncompleted')], default=0),
        ),
    ]
