# Generated by Django 4.0 on 2022-01-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_testorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testorder',
            name='completed',
        ),
    ]
